{
 "title": "myappDashbord",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "myapp_superjob_last_duration" }
   ]
  },
  {
   "title": "Duration 0.005 quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.005, sum(rate(myapp_superjob_duration_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Duration 0.95 quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(myapp_superjob_duration_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}